spring:
  thymeleaf:
    mode: HTML
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_spring_blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: mysqlroot
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
logging:
  level:
    root: warn
    com.aduner: error
  file:
    name: log/log-pro.log
server:
  port: 8081