spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_spring_blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: mysqlroot
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
logging:
  level:
    root: warn
    com.aduner: info
  file:
    name: log/log-dev.log
